### ISSUE TITLE
only large flag created for HOI4 flags

### ISSUE THREAD

**Issue by ScrewDriverPizzaCoder** [PlayerHOI/IWFC#3]

**Comment by PlayerHOI** [comment]
Can you please provide more details? Were you using a local image or an image from the web? Provide a list of actions you've done to reproduce the problem?

**Comment by VulcanShot** [comment]
I had the same problem in the first version. However, in the new release everything seems to be fine :)

**Comment by VulcanShot** [comment]
I'd suggest closing this issue.

**Comment by PlayerHOI** [comment]
> I'd suggest closing this issue.

Yeah seems dead...
